services:
  - type: web
    name: livyflow-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    pythonVersion: "3.10"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000 